apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: harborsupervisor.corp.internal/solar-system/solar-system:v9
        name: solar-system
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
